kafka.brokers:
    - "localhost"

zookeeper.servers:
    - "localhost"

kafka.port: 9092
zookeeper.port: 2181
redis.host: "localhost"
redis.port: 30031
kafka.topic: "ad-events"
kafka.partitions: 1

process.hosts: 1
process.cores: 4